#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "build script must be called with single parameter <base path of git repository>"
    exit 1
fi

BASEDIR="$1"
LIB=column_storage
LIBFILE_R=lib${LIB}.a
LIBFILE_D=lib${LIB}_dbg.a
FILES=(BucketManager ColumnManager TransactionManager Transaction)
CD=`pwd | sed 's#.*/##'`

for f in "${FILES[@]}"; do
    echo "${f}_dbg: "
    clang++ -I$BASEDIR/lib -I$BASEDIR/include `llvm-config --cxxflags` -g3 -O0 -fcxx-exceptions -std=c++14 -c $f.cpp -o ${f}_dbg.o || exit 1
    echo "${f}: "
    clang++ -I$BASEDIR/lib -I$BASEDIR/include `llvm-config --cxxflags` -O3 -fcxx-exceptions -std=c++14 -c $f.cpp -o ${f}.o || exit 1
done

#Release
ar cr ${LIBFILE_R} "${FILES[@]/%/.o}"
ranlib ${LIBFILE_R}
ln -sf ${CD}/${LIBFILE_R} ../${LIBFILE_R}

#Debug
ar cr ${LIBFILE_D} "${FILES[@]/%/_dbg.o}"
ranlib ${LIBFILE_D}
ln -sf ${CD}/${LIBFILE_D} ../${LIBFILE_D}

exit 0
