#!/bin/bash

# define variable "DEBUG=1" to enable debug builds

BASEDIR="../.."
LIB=column_storage
LIBFILE_R=lib${LIB}.a
LIBFILE_D=lib${LIB}_dbg.a
FILES=(BucketManager ColumnManager TransactionManager Transaction)
COMP="g++"
COMPFLAGS=-fexceptions
#COMP=clang++
#COMPFLAGS=`llvm-config --cxxflags` -fcxx-exceptions
CD=`pwd | sed 's#.*/##'`

for f in "${FILES[@]}"; do
    echo "${f}: "
    ${COMP} -I$BASEDIR/lib -I$BASEDIR/include ${COMPFLAGS} -g0 -O3 -std=c++14 -c $f.cpp -o ${f}.o || exit 1
    if [[ $DEBUG -ne 0 ]]; then
        echo "${f}_dbg: "
        ${COMP} -I$BASEDIR/lib -I$BASEDIR/include ${COMPFLAGS} -g3 -O0 -std=c++14 -c $f.cpp -o ${f}_dbg.o || exit 1
    fi
done

#Release
ar cr ${LIBFILE_R} "${FILES[@]/%/.o}"
ranlib ${LIBFILE_R}
ln -sf ${CD}/${LIBFILE_R} ../${LIBFILE_R}

#Debug
if [[ $DEBUG -ne 0 ]]; then
    ar cr ${LIBFILE_D} "${FILES[@]/%/_dbg.o}"
    ranlib ${LIBFILE_D}
    ln -sf ${CD}/${LIBFILE_D} ../${LIBFILE_D}
fi

exit 0
