#!/bin/bash

LIB=column_operators
LIBFILE=lib${LIB}.a
FILES=(operators)
CD=`pwd | sed 's#.*/##'`

for f in "${FILES[@]}"; do
        clang++ -I/home/tk4/git/columnstore/lib -I/home/tk4/git/columnstore/include `llvm-config --cxxflags` -std=c++14 -c $f.cpp -o $f.o
done

#libtool -static operators.o -o liboperators.a
ar cru ${LIBFILE} "${FILES[@]/%/.o}"
ranlib ${LIBFILE}
ln -sf ${CD}/${LIBFILE} ../${LIBFILE}

