#!/bin/bash

BASEDIR="../.."
LIB=util
LIBFILE_R=lib${LIB}.a
LIBFILE_D=lib${LIB}_dbg.a
FILES=(stopwatch resilience rss)
COMP="g++"
COMPFLAGS=-fexceptions
#COMP=clang++
#COMPFLAGS=`llvm-config --cxxflags` -fcxx-exceptions
CD=`pwd | sed 's#.*/##'`

for f in "${FILES[@]}"; do
    echo "${f}_dbg: "
    ${COMP} -I$BASEDIR/lib -I$BASEDIR/include ${COMPFLAGS} -g3 -O0 -std=c++14 -c $f.cpp -o ${f}_dbg.o || exit 1
    echo "${f}: "
    ${COMP} -I$BASEDIR/lib -I$BASEDIR/include ${COMPFLAGS} -g0 -O3 -std=c++14 -c $f.cpp -o ${f}.o || exit 1
done

#Release
ar cr ${LIBFILE_R} "${FILES[@]/%/.o}"
ranlib ${LIBFILE_R}
ln -sf ${CD}/${LIBFILE_R} ../${LIBFILE_R}

#Debug
ar cr ${LIBFILE_D} "${FILES[@]/%/_dbg.o}"
ranlib ${LIBFILE_D}
ln -sf ${CD}/${LIBFILE_D} ../${LIBFILE_D}

exit 0
